name: build & test

env:
    IMAGE_PREFIX: "ghcr.io/dnkpp/"

on:
    push:
        branches: [master, dev]
    pull_request:
        branches: [master, dev]

jobs:
    build:
        name: ${{ matrix.config.name }} ${{ matrix.config.compiler_name }}-${{ matrix.config.compiler_version }} C++${{ matrix.config.cxx_standard }} (${{ matrix.build_mode }})
        runs-on: ${{ matrix.config.os }}
        container:
            image: ghcr.io/dnkpp/${{ matrix.config.compiler_name }}:${{ matrix.config.compiler_version }}

        strategy:
            fail-fast: false
            matrix:
                build_mode: [Debug, Release]
                config:
                    #clang-18
                    - {
                        name: "Linux",
                        os: ubuntu-latest,
                        compiler_name: clang,
                        compiler_version: 18,
                        cxx_standard: 23
                    }
                    - {
                        name: "Linux",
                        os: ubuntu-latest,
                        compiler_name: clang,
                        compiler_version: 18,
                        cxx_standard: 20
                    }
                    #clang-17
                    - {
                        name: "Linux",
                        os: ubuntu-latest,
                        compiler_name: clang,
                        compiler_version: 17,
                        cxx_standard: 23
                    }
                    - {
                        name: "Linux",
                        os: ubuntu-latest,
                        compiler_name: clang,
                        compiler_version: 17,
                        cxx_standard: 20
                    }
                    #clang-16
                    - {
                        name: "Linux",
                        os: ubuntu-latest,
                        compiler_name: clang,
                        compiler_version: 16,
                        cxx_standard: 23
                    }
                    - {
                        name: "Linux",
                        os: ubuntu-latest,
                        compiler_name: clang,
                        compiler_version: 16,
                        cxx_standard: 20
                    }
                    #clang-15
                    - {
                        name: "Linux",
                        os: ubuntu-latest,
                        compiler_name: clang,
                        compiler_version: 15,
                        cxx_standard: 23
                    }
                    - {
                        name: "Linux",
                        os: ubuntu-latest,
                        compiler_name: clang,
                        compiler_version: 15,
                        cxx_standard: 20
                    }
                    #clang-14
                    - {
                        name: "Linux",
                        os: ubuntu-latest,
                        compiler_name: clang,
                        compiler_version: 14,
                        cxx_standard: 23
                    }
                    - {
                        name: "Linux",
                        os: ubuntu-latest,
                        compiler_name: clang,
                        compiler_version: 14,
                        cxx_standard: 20
                    }

        steps:
            - uses: actions/checkout@v4
  
            - name: Compile tests
              run: |
                cmake \
                -D CMAKE_BUILD_TYPE=${{ matrix.build_mode }} \
                -D CMAKE_VERBOSE_MAKEFILE=yes \
                -D mimicpp_BUILD_TESTS=yes \
                -D mimicpp_FORCED_CXX_STANDARD=${{ matrix.config.cxx_standard }} \
                -B build -S .

                cmake --build build -j4

            - name: Run tests
              env:
                CTEST_OUTPUT_ON_FAILURE: 1
              run: ctest --test-dir build/test -C ${{ matrix.build_mode }} -j4
