name: generate amalgamated header

on:
    push:
        branches: [main, development]
    pull_request:
        branches: [main, development]
    release:
        types: [released]

jobs:
  amalgamate-header:
    runs-on: ubuntu-latest
    container:
        image: ghcr.io/dnkpp/gcc:14

    steps:
    - uses: actions/checkout@v4

    - name: Configure
      run: |
        cmake \
            -S . \
            -B build \
            --log-level=VERBOSE \
            -DMIMICPP_ENABLE_AMALGAMATE_HEADERS=ON \
            -DMIMICPP_BUILD_TESTS=OFF \
            -DMIMICPP_BUILD_EXAMPLES=OFF

    - name: Generate Doxygen Documentation
      run: |
        cmake --build build --target mimicpp-amalgamate-headers

    - name: Upload header
      uses: actions/upload-artifact@v4
      with:
        name: amalgamated-header
        path: build/tools/amalgamate-headers/mimic++-amalgamated.hpp

  release-amalgamated-header:
    runs-on: ubuntu-latest
    needs: amalgamate-header
    if: ${{ github.event_name == 'release' }}

    # this is required for the asset attachment
    permissions:
      contents: write

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: amalgamated-header
        path: ./header
  
    - name: attach release assets
      uses: ncipollo/release-action@v1
      with:
        artifacts: "header/mimic++-amalgamated.hpp"
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        artifactErrorsFailBuild: true
