name: generate build matrix
on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  generate-matrix:
    runs-on: ubuntu-latest

    outputs:
      config: ${{ steps.output-config.outputs.config }}
      build_modes: ${{ steps.output-options.outputs.build_modes }}
      cxx_versions: ${{ steps.output-options.outputs.cxx_versions }}

    steps:
      # enables debug-mode and c++20 for all cases
      - name: Enable base matrix
        shell: bash
        run: |
          echo "BUILD_MODES=\"Debug\"" >> $GITHUB_ENV
          echo "CXX_VERSIONS=20" >> $GITHUB_ENV

      # if its a PR from development or the main branch in general, add release-mode and c++23
      - name: Enable extended matrix
        if: ${{
          (github.event_name == 'pull_request' && github.head_ref == 'development')
          || github.ref_name == 'main'
          }}
        shell: bash
        run: |
          echo "BUILD_MODES=$(echo $BUILD_MODES, \"Release\")" >> $GITHUB_ENV
          echo "CXX_VERSIONS=$(echo $CXX_VERSIONS, 23)" >> $GITHUB_ENV

      - name: Output build-modes and c++-versions
        id: output-options
        shell: bash
        run: |
          echo "build_modes=$(echo [ $BUILD_MODES ])" >> "$GITHUB_OUTPUT"
          echo "cxx_versions=$(echo [ $CXX_VERSIONS ])" >> "$GITHUB_OUTPUT"
